### ISSUE TITLE
Search export bug

### ISSUE THREAD

**Issue by ghost** [vinikira/netsuite-toolbox#1]
For some unknown reason when loading a search you don't usually need to pass in the search type even tho it it is marked as mandatory in the API. However if you want to load a search for certain types like deleted records, you get an unknown error if you miss out the search type. 
replace line 60 in page-javascript-context.js
with
```
const currentSearch = search.load({type: currentRecord.getValue('searchtype'),  id: currentRecord.id})
```

**Comment by vinikira** [comment]
Thank you for bug report. Your code has been inserted into specified file, and a new version will soon be  available in the Firefox Add-ons with the fix.
